name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      # This seems too broad a permission for only creating a release. What could possibly go wrong?
      # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2026-03-10#repository-permissions-for-contents
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: create zip
        run: |
          sudo apt-get install zip &&
          pushd dist &&
          zip -r tarot-cards-for-vtt.zip ./* &&
          mv tarot-cards-for-vtt.zip ../ &&
          popd
      - name: Release (draft)
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          generate_release_notes: true
          working_directory: dist
          files: |
            module.json
            tarot-cards-for-vtt.zip
      # TODO: autopublish to foundry registry?
