name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      # This seems too broad a permission for only creating a release. What could possibly go wrong?
      # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2026-03-10#repository-permissions-for-contents
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: create zip
        run: |
          sudo apt-get install zip &&
          pushd dist &&
          zip -r tarot-cards-for-vtt.zip ./* &&
          mv tarot-cards-for-vtt.zip ../ &&
          popd
      - name: Create Release (draft)
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Add module.json to Release
        id: upload_module_json
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/module.json
          asset_name: module.json
          asset_content_type: applicaton/json
      - name: Add zip to Release
        id: upload_release_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tarot-cards-for-vtt.zip
          asset_name: tarot-cards-for-vtt.zip
          asset_content_type: application/zip
      # TODO: autopublish to foundry registry?
